// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbosucyfznpbwotjqvfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJib3N1Y3lmem5wYndvdGpxdmZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0ODk0NjUsImV4cCI6MjA1NDA2NTQ2NX0.q3PCVvsbPXS-72261cAJmUit06JglNNaZL6hXcHX9Iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);